# Generated by Django 5.2.8 on 2025-11-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examstudent',
            name='question_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
